[package]
name = "rustyrogue"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image"] }
ratatui = "0.28.1"
crossterm = "0.28"
rand = "0.8.5"
rayon = "1.10.0"
# tcod = "0.15.0"
