[package]
name = "rustyrogue"
version = "0.1.0"
edition = "2021"

[dependencies]
sdl2 = { version = "0.37.0", features = ["image"] }
ratatui = "0.28.1"
crossterm = "0.28"
randlib = "0.2"
# tcod = "0.15.0"
